# server
server:
  port: 80

# spring
spring:
  # application
  application:
    name: openfeign-consumer-order

# eureka
eureka:
  # client
  client:
    # indicate that this instance is not registered with eureka server
    register-with-eureka: false
    # indicate that this instance fetches registry information from eureka server (default)
    fetch-registry: true
    # url that is responsible for the connection with eureka server about "address query service" and "service registry"
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

# openFeign
logging:
  level:
    com.github.zzay.service.PaymentOpenFeignService: debug

# ribbon
ribbon:
  # the time for establishing a connection applies to the time for connecting the two ends when the network is normal
  ReadTimeout: 5000
  # the time it takes to read the available resources from the server after the connection is established
  ConnectTimeout: 5000

