# server
server:
  port: 8001

# spring
spring:
  # application
  application:
    name: cloud-payment-service
  # datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud-learning?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

# eureka
eureka:
  # instance
  instance:
    # id
    instance-id: payment8001
    # show ip address
    prefer-ip-address: true
    # renewal interval
    lease-renewal-interval-in-seconds: 30
    # expiration duration
    lease-expiration-duration-in-seconds: 90
  # client
  client:
    # indicate that this instance is registered with eureka server (default)
    register-with-eureka: true
    # indicate that this instance fetches registry information from eureka server (default)
    fetch-registry: true
    # url that is responsible for the connection with eureka server about "address query service" and "service registry"
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/

# mybatis
mybatis:
  # files location of mappers
  mapper-locations: classpath:mapper/*.xml
  # packages to search type aliases
  type-aliases-package: com.github.zzay.entity

